# SRC: https://linuxconfig.org/how-to-network-connect-two-containers-with-docker-compose
networks:
  shared_network:

services:
  rest-app:
    build:
      context: ./node/rest-app
      target: json-server
    command: start
    ports:
      - 3000:3000

  # TODO enable when Streamable HTTP
  # mcp-server.examples.quick-start:
  #   build:
  #     context: ./node/mcp-server.examples.quick-start
  #     target: mcp-server
  #   command: start
  #   stdin_open: true
  #   ports:
  #     - 4001:3000

  # FIXME change to [Streamable]HTTPServerTransport
  mcp-server.rest-app.posts:
    depends_on:
      - rest-app
    build:
      context: ./node/mcp-server.rest-app.posts
      target: mcp-server
    command: start:http:stateless
    stdin_open: true
    ports:
      - 4002:3000

  modelcontextprotocol.inspector:
    # NOTE: If you want to build it from `npm install`
    # build:
    #   target: modelcontextprotocol.inspector
    #
    # NOTE: Using the pre-built image from GitHub Container Registry
    image: ghcr.io/modelcontextprotocol/inspector:latest
    # command: ["--config", "/app/mcp.json"] # Point to a configuration file if needed
    #
    # List all MCP servers so that the inspector can connect to them
    depends_on:
      # - mcp-server.examples.quick-start  # TODO
      - mcp-server.rest-app.posts
    ports:
      - 6274:6274
      - 6277:6277
    #
    # ISSUE
    # SRC: https://github.com/modelcontextprotocol/inspector/issues/788
    env_file:
      - .env.development
      - .env.local


  semantic-kernel-sampler-py:
    depends_on:
      - mcp-server.rest-app.posts
    build:
      context: ./python/semantic-kernel-sampler-py
      target: release
    ports:
      - 8082:9999
    env_file:
      - .env.development
      - .env.local

  agent-framework-sampler-py:
    depends_on:
      - mcp-server.rest-app.posts
    build:
      context: ./python/agent-framework-sampler-py
      target: release
    ports:
      - 8082:9999
    env_file:
      - .env.development
      - .env.local


  semantic-kernel-sampler.net:
    depends_on:
      - semantic-kernel-sampler-py
    build:
      context: ./dotnet
      target: webapp
    ports:
      - 8083:8080
      - 8483:8081
    env_file:
      - .env.development
      - .env.local

  # TODO? XXX? java-app:

  # TODO? XXX? typescript-app?:

  a2a-inspector:
    build:
      context: ./repositories/a2a-inspector
    ports:
      - 5001:8080
    depends_on:
      - semantic-kernel-sampler-py
      - agent-framework-sampler-py
      # - semantic-kernel-sampler-dotnet
