services:
  rest-app:
    build:
      context: .
      target: rest-app
    command: start
    ports:
      - 8080:3000

  # TODO typescript-app:

  python-app:
    build:
      context: ./python
      target: release
    # TODO
    # ports:
    #   - 8082:3000

  dotnet-app:
    build:
      context: ./dotnet
      target: webapp
    ports:
      - 8083:8080
