# SRC: https://linuxconfig.org/how-to-network-connect-two-containers-with-docker-compose
networks:
  shared_network:

services:
  rest-app:
    build:
      context: .
      target: rest-app
    command: start
    ports:
      - 3000:3000

  semantic-app-py:
    build:
      context: ./python/semantic-kernel-sampler-py
      target: release
    ports:
      - 8082:9999

  semantic-app.net:
    build:
      context: ./dotnet
      target: webapp
    ports:
      - 8083:8080

  # TODO java-app:

  # TODO typescript-app?:

  a2a-inspector:
    build:
      context: ./repositories/a2a-inspector
    ports:
      - 5001:8080
    depends_on:
      - semantic-app-py
      # - semantic-app-dotnet
