# SRC: https://linuxconfig.org/how-to-network-connect-two-containers-with-docker-compose
networks:
  shared_network:

services:
  rest-app:
    build:
      context: ./node/rest-app
      target: json-server
    command: start
    ports:
      - 3000:3000

  mcp-server.examples.getting_started:
    build:
      context: ./node/mcp-server.examples.getting_started
      target: mcp-server
    command: start
    stdin_open: true
    ports:
      - 4001:3000

  # FIXME change to [Streamable]HTTPServerTransport
  mcp-server.rest-app.posts:
    depends_on:
      - rest-app
    build:
      context: ./node/mcp-server.rest-app.posts
      target: mcp-server
    command: start
    stdin_open: true
    ports:
      - 4002:3000

  semantic-app-py:
    depends_on:
      - mcp-server.rest-app.posts
    build:
      context: ./python/semantic-kernel-sampler-py
      target: release
    ports:
      - 8082:9999

  semantic-app.net:
    build:
      context: ./dotnet
      target: webapp
    ports:
      - 8083:8080

  # TODO java-app:

  # TODO typescript-app?:

  a2a-inspector:
    build:
      context: ./repositories/a2a-inspector
    ports:
      - 5001:8080
    depends_on:
      - semantic-app-py
      # - semantic-app-dotnet
