services:
  rest-app:
    build:
      context: .
      target: rest-app
    command: start
    ports:
      - 8080:3000

  # TODO typescript-app:

  semantic-app-python:
    build:
      context: ./python/semantic-kernel-sampler-py
      target: release
    ports:
      - 8082:9999

  semantic-app-dotnet:
    build:
      context: ./dotnet
      target: webapp
    ports:
      - 8083:8080
