"""
This type stub file was generated by pyright.
"""

from hamcrest.core.assert_that import assert_that
from hamcrest.core.core import *

__author__ = ...
__copyright__ = ...
__license__ = ...
__all__ = ["assert_that", "all_of", "any_of", "anything", "calling", "described_as", "equal_to", "instance_of", "is_", "is_not", "none", "not_", "not_none", "raises", "same_instance"]
