"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable
from hamcrest.core.description import Description

__author__ = ...
__copyright__ = ...
__license__ = ...
class BaseDescription(Description):
    """Base class for all :py:class:`~hamcrest.core.description.Description`
    implementations.

    """
    def append_text(self, text: str) -> Description:
        ...
    
    def append_description_of(self, value: Any) -> Description:
        ...
    
    def append_list(self, start: str, separator: str, end: str, list: Iterable[Any]) -> Description:
        ...
    
    def append(self, string: str) -> None:
        """Append the string to the description."""
        ...
    
    def append_string_in_python_syntax(self, string: str) -> None:
        ...
    


def character_in_python_syntax(ch: str) -> str:
    ...

