"""
This type stub file was generated by pyright.
"""

from hamcrest.core.description import Description

__author__ = ...
__copyright__ = ...
__license__ = ...
class SelfDescribing:
    """The ability of an object to describe itself."""
    def describe_to(self, description: Description) -> None:
        """Generates a description of the object.

        The description may be part of a description of a larger object of
        which this is just a component, so it should be worded appropriately.

        :param description: The description to be built or appended to.

        """
        ...
    


