"""
This type stub file was generated by pyright.
"""

from hamcrest.core.selfdescribing import SelfDescribing
from .base_description import BaseDescription

__author__ = ...
__copyright__ = ...
__license__ = ...
def tostring(selfdescribing: SelfDescribing) -> str:
    """Returns the description of a
    :py:class:`~hamcrest.core.selfdescribing.SelfDescribing` object as a
    string.

    :param selfdescribing: The object to be described.
    :returns: The description of the object.
    """
    ...

class StringDescription(BaseDescription):
    """A :py:class:`~hamcrest.core.description.Description` that is stored as a
    string.

    """
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        """Returns the description."""
        ...
    
    def append(self, string: str) -> None:
        ...
    


