"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Tuple
from hamcrest.core.base_matcher import BaseMatcher
from hamcrest.core.description import Description
from hamcrest.core.matcher import Matcher

__author__ = ...
__copyright__ = ...
__license__ = ...
ARG_PATTERN = ...
class DescribedAs(BaseMatcher[Any]):
    def __init__(self, description_template: str, matcher: Matcher[Any], *values: Tuple[Any, ...]) -> None:
        ...
    
    def matches(self, item: Any, mismatch_description: Optional[Description] = ...) -> bool:
        ...
    
    def describe_mismatch(self, item: Any, mismatch_description: Description) -> None:
        ...
    
    def describe_to(self, description: Description) -> None:
        ...
    


def described_as(description: str, matcher: Matcher[Any], *values) -> Matcher[Any]:
    """Adds custom failure description to a given matcher.

    :param description: Overrides the matcher's description.
    :param matcher: The matcher to satisfy.
    :param value1,...: Optional comma-separated list of substitution values.

    The description may contain substitution placeholders %0, %1, etc. These
    will be replaced by any values that follow the matcher.

    """
    ...

