"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from hamcrest.core.base_matcher import BaseMatcher
from hamcrest.core.description import Description
from hamcrest.core.matcher import Matcher

__author__ = ...
__copyright__ = ...
__license__ = ...
class IsAnything(BaseMatcher[Any]):
    def __init__(self, description: Optional[str]) -> None:
        ...
    
    def describe_to(self, description: Description) -> None:
        ...
    


def anything(description: Optional[str] = ...) -> Matcher[Any]:
    """Matches anything.

    :param description: Optional string used to describe this matcher.

    This matcher always evaluates to ``True``. Specify this in composite
    matchers when the value of a particular element is unimportant.

    """
    ...

