"""
This type stub file was generated by pyright.
"""

from typing import Type
from hamcrest.core.base_matcher import BaseMatcher
from hamcrest.core.description import Description
from hamcrest.core.matcher import Matcher

__author__ = ...
__copyright__ = ...
__license__ = ...
class IsInstanceOf(BaseMatcher[object]):
    def __init__(self, expected_type: Type) -> None:
        ...
    
    def describe_to(self, description: Description) -> None:
        ...
    


def instance_of(atype: Type) -> Matcher[object]:
    """Matches if object is an instance of, or inherits from, a given type.

    :param atype: The type to compare against as the expected type.

    This matcher checks whether the evaluated object is an instance of
    ``atype`` or an instance of any class that inherits from ``atype``.

    Example::

        instance_of(str)

    """
    ...

