context_parser: pypyr.parser.keyvaluepairs
steps:
  - name: pypyr.steps.echo
    in:
      echoMe: "= pypyr dev =================================================="
  - name: pypyr.steps.default
    comment: set default values for optional cli inputs
    in:
      defaults:
        path: .
        clean: False
        style: True
        lint: True
        test: True
        integration: False
        stats: False

  - name: pypyr.steps.shell
    in:
      cmd: "python -m pypyr qa path={path} clean={clean} style={style} lint={lint} test={test} integration={integration} stats={stats}"
