"""
This type stub file was generated by pyright.
"""

from hamcrest.core import *
from hamcrest.library import *
from hamcrest import core, library
from hamcrest._version import version

__version__ = ...
__author__ = ...
__copyright__ = ...
__license__ = ...
__all__ = []
