[tasks]
    [tasks.clean]
        help = "Clean the project"
        cmd = "uvx pyclean src"

    # clean code tasks
    [tasks.ruff_format]
        cmd = "ruff format ./src"
        help = "format codebase with ruff"

    [tasks.ruff_check-fix]
        cmd = "ruff check --fix ./src"
        help = "fix codebase with ruff"

    [tasks.ruff_check]
        cmd = "ruff check ./src"
        help = "lint codebase with ruff"

    [tasks.uv-sort]
        cmd = "uv run uv-sort"
        help = "fixes order of imports"

    [tasks.uv-sort_check]
        cmd = "uv run uv-sort --check"
        help = "Checks if uv-sort was fixed"

    [tasks.pyright]
        cmd = "uv run pyright --warnings"
        help = "Checks type hints with pyright"

    [tasks.lint]
        help = "Checks linting"
        sequence = ["uv-sort_check", "ruff_check", "pyright"]

    [tasks.style]
        help = "Reformat"
        sequence = ["uv-sort", "ruff_format", "ruff_check-fix", "lint"]


    [tasks.ci]
    help = "Run the CI pipeline tasks"
    sequence = ["lint"]

    [tasks.dev]
    help = "Run the development tasks"
    sequence = ["clean", "style"]

    [tasks.build]
    help = "Build the project"
    cmd = "uv build --all-packages --wheel"

    [tasks.sync]
    help = "uv sync everything"
    cmd = "uv sync --locked --all-extras"
